"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./ReduxProvider";
import { AuthProvider } from "./UseAuthProvider";
import "@/styles/reset.css";
import styled from "styled-components";
import theme from "@/styles/theme";
import { Suspense } from "react";
import Loading from "./loading";
const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Container = styled.div`
  background-color: ${theme.colors.lightGrey};
`;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <ReduxProvider>
          <AuthProvider>
            <Container>{children}</Container>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
